from typing import Any, Optional, List, Dict

class SerdeJSON:
    def __init__(self) -> None: ...

    def get(self, obj: Any, key: str) -> Any: ...
    def set(self, obj: Any, key: Any, value: Any) -> Any: ...

    def to_json(self, obj: Any) -> str: ...
    def to_json_pretty(self, obj: Any) -> str: ...
    def to_bytes(self, obj: Any) -> bytes: ...
    def to_bytes_pretty(self, obj: Any) -> bytes: ...

    def from_json(self, json_str: str) -> Any: ...
    def from_bytes(self, b: bytes) -> Any: ...

    def is_null(self, obj: Any) -> bool: ...
    def is_boolean(self, obj: Any) -> bool: ...
    def is_number(self, obj: Any) -> bool: ...
    def is_string(self, obj: Any) -> bool: ...
    def is_array(self, obj: Any) -> bool: ...
    def is_object(self, obj: Any) -> bool: ...
    def is_i64(self, obj: Any) -> bool: ...
    def is_u64(self, obj: Any) -> bool: ...
    def is_f64(self, obj: Any) -> bool: ...

    def as_bool(self, obj: Any) -> Optional[bool]: ...
    def as_i64(self, obj: Any) -> Optional[int]: ...
    def as_u64(self, obj: Any) -> Optional[int]: ...
    def as_f64(self, obj: Any) -> Optional[float]: ...
    def as_str(self, obj: Any) -> Optional[str]: ...

    def merge(self, a: Any, b: Any) -> Any: ...
    def get_path(self, obj: Any, path: List[str]) -> Any: ...
    def pointer(self, obj: Any, pointer: str) -> Any: ...
    def flatten(self, obj: Any) -> Dict[str, Any]: ...
    def keys(self, obj: Any, recursive: Optional[bool] = None) -> List[str]: ...
    def values(self, obj: Any, recursive: Optional[bool] = None) -> List[Any]: ...
    def count_values(self, obj: Any) -> int: ...
    def find_paths(self, obj: Any, target: Any) -> List[List[str]]: ...
    def remove_nulls(self, obj: Any) -> Any: ...
    def sort_keys(self, obj: Any) -> Any: ...
    def depth(self, obj: Any) -> int: ...

    def validate(self, json_str: str) -> bool: ...
    def minify(self, json_str: str) -> str: ...
    def equals(self, a: Any, b: Any) -> bool: ...
    def size(self, obj: Any) -> int: ...
    